### ISSUE TITLE
Have you all ever thought about creating a website with  vala-gtk-examples? 

### ISSUE THREAD

**Issue by ghost** [gerito1/vala-gtk-examples#4]
Hi all! 

I would like to have a website where I could store visual models written in vala, genie etc. Partly because by having a website where I can share my GTK visuals, other people could have access and avoid junk.

An interesting option is web components which is a website/organization that is responsible for standardizing visual web components, in addition to this responsibility, there is also the idea of collaboration and reuse of different types of components

This project here I consider to be innovative and also a starting point for creating a site to share visual components in different projects that need gtk. 

So... ***have you all ever thought about creating a website with vala-gtk-examples for facilitate the creation of mockups, software prototypes in a linux environment natively?***

**Note:** *Initially, you can create a repository for GitHub components. But the problem with this is that it's not something from the community - I mean it's not hosted on a server where we can have different types of access control, management, data. It's not something for the community. But... my goal here would be to use these visual components and distribute them over the network to various open source projects. For this objective to be possible, it should have a specific server for this - not just a stored repository.*

**Comment by gerito1** [comment]
Yes I thought about having mock ups, specially considering there is a huge variety of "look and feel" flavors in gtk world, but not a site.

But yeah. Having mock ups for all the components would be a huge help.

Also I really don't have a road map, this is ad hoc but it is a good idea.
